### PR TITLE
Set default paginator in ENV so specs don't fail without it

### PR DESCRIPTION
**Pull request by codeodor**
Following the discussion in #55, since it hadn't been touched in months, I implemented the suggested solution so I could get my local specs passing.

### CODE REVIEW

**Comment by davidcelis** [comment]
This looks good to me, but it looks like there's a version incompatibility with Rack on earlier Ruby versions. Given that 2.1.x will be EOL'd soon and everything before it has already been EOL'd, would you mind just changing the ruby versions to only be these?

```yaml
rvm:
  - 2.2
  - 2.3
```

I think that leaving the patch version out will just default to the latest, so we should be good 👍

**Comment by davidcelis** [comment]
Well that's silly. I guess I was wrong 😓 looks like patch versions still have to be specified:

```yaml
rvm:
  - 2.2.5
  - 2.3.1
```

**Comment by davidcelis** [comment]
Thanks so much, @codeodor! Sorry about the runaround!

**Comment by codeodor** [comment]
No worries. Thank you!

**Pull request merged**
